[versions]
# BOM Versions
spring-ai-dependencies = "1.1.2"
spring-boot-dependencies = "3.5.9"
spring-cloud-dependencies = "2025.0.0"
spring-cloud-gcp-dependencies = "7.4.2"

# Runtime Versions
bson = "5.6.2"
jooq = "3.20.10"
kotlin-logging = "7.0.14"
ksp = "2.3.4"
meilisearch = "0.17.1"
springdoc-openapi = "2.8.14"
tess4j = "5.17.0"

# Test Versions
approvaltests = "26.1.0"
cucumber = "7.33.0"
io-rest-assured = "6.0.0"
kotest = "6.0.7"
kotlin-faker = "1.16.0"
testcontainers-meilisearch = "1.0.5"


[libraries]
# BOM Dependencies
spring-ai-dependencies-bom = { module = "org.springframework.ai:spring-ai-bom", version.ref = "spring-ai-dependencies" }
spring-boot-dependencies-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot-dependencies" }
spring-cloud-dependencies-bom = { module = "org.springframework.cloud:spring-cloud-dependencies", version.ref = "spring-cloud-dependencies" }
spring-cloud-gcp-dependencies-bom = { module = "com.google.cloud:spring-cloud-gcp-dependencies", version.ref = "spring-cloud-gcp-dependencies" }

# Runtime Dependencies
bson = { module = "org.mongodb:bson", version.ref = "bson" }
jooq = { module = "org.jooq:jooq", version.ref = "jooq" }
kotlin-logging-jvm = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }
ksp-symbol-processing-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
meilisearch-java-client = { module = "com.meilisearch.sdk:meilisearch-java", version.ref = "meilisearch" }
springdoc-openapi-starter-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc-openapi" }
tess4j = { module = "net.sourceforge.tess4j:tess4j", version.ref = "tess4j" }

# Test Dependencies
approvaltests = { module = "com.approvaltests:approvaltests", version.ref = "approvaltests" }
cucumber-java = { module = "io.cucumber:cucumber-java", version.ref = "cucumber" }
cucumber-junit = { module = "io.cucumber:cucumber-junit", version.ref = "cucumber" }
cucumber-spring = { module = "io.cucumber:cucumber-spring", version.ref = "cucumber"}
io-rest-assured = { module = "io.rest-assured:rest-assured", version.ref = "io-rest-assured" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotlin-faker = { module = "io.github.serpro69:kotlin-faker", version.ref = "kotlin-faker" }
testcontainers-meilisearch = { module = "io.vanslog:testcontainers-meilisearch", version.ref = "testcontainers-meilisearch" }
